NO_TARGET_TIMEOUT_STATE = 4.0
NO_TARGET_TIMEOUT = 3.0

HANDLER_NAMES = {
        'TagsDetectorHandler': 'tag_id',
}

MAXIMUM_VALID_TIME_DETECTION = 0.2
X_THRESHOLD_ERROR = 0.02
Y_THRESHOLD_ERROR = 0.02
FIND_TAGS_ANGULAR_VELOCITY = 8
EPSILON= 1e-9