from .constants import *

ERROR_INVALID_ANGLE = (1, f'Invalid angle, must be between -180 and 180')
ERROR_INVALID_PREDICTOR = (2, f'Invalid predictor')
ERROR_IDENTIFIER_NOT_DEFINED = (3, f'Identifier must be defined')
ERROR_NO_TARGET_FOUND = (4, f'Not target found after {NO_TARGET_TIMEOUT}')
ERROR_TOO_DISALIGNED = 5
ERROR_TOO_CLOSE_TO_TARGET = 6
ERROR_TOO_FAR_TO_TARGET = 7
ERROR_IDENTIFIER_LENGTH_HAS_BEEN_EXCEED = (8, 
                                           'Maximum length of identifier is 2')
ERROR_MOVING = 9
ERROR_DISTANCE_TO_CORRECT_TOO_HIGH = 10
ERROR_FINAL_ERROR_Y_NOT_ACCOMPLISHED = 11

ERROR_NOT_TAG_FOUND_SCAN_RIGHT = 12
ERROR_NOT_TAG_FOUND_ROTATE_UNTIL_LOOK_TAGS = 13
ERROR_NOT_TAG_FOUND_ROTATE_UNTIL_LOOK_TAGS_N = 14
ERROR_NOT_TAG_FOUND_READ_APRILTAGS_CENTER = 15
ERROR_NOT_TAG_FOUND__ROTATE_UNTIL_LOOK_TAGS_FINAL = 16